### ISSUE TITLE
로딩속도 최적화

### ISSUE THREAD

**Issue by simnalamburt** [simnalamburt/game.hyeon.me#1]
- [x] 폰트에서 필요한 글리프만 남기고 다 지워서 용량 줄이기.
    - [x] "KoPub Batang" 폰트 알파벳/특문과 KS C 5601 글자만 남기기. Times New Roman 폴백 더이상 안함
    - [x] "Noto Sans KR" 폰트 알파벳/특문과 KS C 5601 글자만 남기기. Poppins 폴백 더이상 안함
- [x] ~~Poppins-Medium 폰트 woff2 woff eot 기타등등으로 변환하기~~ &rarr; 쓰지 않게 되었음
- [x] ~~"일시정지" 글자 SVG로 박기~~ &rarr; 맑은고딕 혹은 애플고딕으로 렌더링하도록 수정
- [x] Linux, OS X 에서 폰트 렌더링 괜찮은지 테스트
    - [x] ~~OS X 크롬, 아예 실행안됨~~ &rarr; #5 
    - [x] OS X 파이어폭스, 폰트 폴백에 문제있어서 글자 안그려짐
- [x] ~~Webpack 넣기~~ &rarr; #8 
- [x] ~~폰트 로딩시점 화면 렌더링 끝난 뒤에 비동기적으로 하도록 수정~~ &rarr; #10
